### ISSUE TITLE
Error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by baprx** [yuzushioh/BittrexKit#3]
Hi,
Thank you for this project, it will surely help me as soon as I resolve a problem that happens every time when I want to use BittrexKit :
```
Undefined symbols for architecture x86_64:
  "__T06APIKit16SessionTaskErrorON", referenced from:
      __T08BitTrade14ViewControllerC11viewDidLoadyyFy6ResultAEOy10BittrexKit19GetBalancesResponseV6APIKit16SessionTaskErrorOGcfU_ in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Do you know what can be the cause ?

**Comment by yuzushioh** [comment]
Hi @BapRx. Thank you for the issue. I will check it as soon as possible. Could you give me the lines of code you are writing please?

**Comment by baprx** [comment]
Ok thank you for your work !
________________________________
De : Ryo Fukuda <notifications@github.com>
Envoyé : jeudi 4 janvier 2018 16:46
À : yuzushioh/BittrexKit
Cc : BapRx; Mention
Objet : Re: [yuzushioh/BittrexKit] Error: linker command failed with exit code 1 (#3)


Hi @BapRx<https://github.com/baprx>. Thank you for the issue. I will check it as soon as possible. will let you know when its fixed!

**Comment by yuzushioh** [comment]
I edited the comment afterwards so you might see the older comment. Could you share the codes where you use BittrexKit in your project? It’ll help me debug👍🏻
